// This JavaScript file was generated by Yggdrassil on Wednesday, May 8, 2024; 7:12:21 PM

let PageLangs = {}
PageLangs.List=[]
PageLangs.Names={}

PageLangs.List[PageLangs.List.length] = 'NL'
PageLangs.Names['NL']='Dutch'

