// This JavaScript file was generated by Yggdrassil on Sunday, December 19, 2021; 12:33:04 PM

let PageLangs = {}
PageLangs.List=[]
PageLangs.Names={}

PageLangs.List[PageLangs.List.length] = 'NL'
PageLangs.Names['NL']='Dutch'

