// This JavaScript file was generated by Yggdrassil on Saturday, October 1, 2022; 10:41:16 PM

let PageLangs = {}
PageLangs.List=[]
PageLangs.Names={}

PageLangs.List[PageLangs.List.length] = 'NL'
PageLangs.Names['NL']='Dutch'

