// This JavaScript file was generated by Yggdrassil on Saturday, February 3, 2024; 6:14:56 PM

let PageLangs = {}
PageLangs.List=[]
PageLangs.Names={}

PageLangs.List[PageLangs.List.length] = 'NL'
PageLangs.Names['NL']='Dutch'

PageLangs.List[PageLangs.List.length] = 'EN'
PageLangs.Names['EN']='English'

