// This JavaScript file was generated by Yggdrassil on Sunday, August 18, 2024; 12:51:34 PM

let PageLangs = {}
PageLangs.List=[]
PageLangs.Names={}

PageLangs.List[PageLangs.List.length] = 'NL'
PageLangs.Names['NL']='Dutch'

