// This JavaScript file was generated by Yggdrassil on Sunday, August 18, 2024; 8:46:07 PM

let PageLangs = {}
PageLangs.List=[]
PageLangs.Names={}

PageLangs.List[PageLangs.List.length] = 'NL'
PageLangs.Names['NL']='Dutch'

