// This JavaScript file was generated by Yggdrassil on Thursday, June 8, 2023; 5:44:28 PM

let PageLangs = {}
PageLangs.List=[]
PageLangs.Names={}

PageLangs.List[PageLangs.List.length] = 'NL'
PageLangs.Names['NL']='Dutch'

