// This JavaScript file was generated by Yggdrassil on Tuesday, December 24, 2024; 10:41:34 PM

let PageLangs = {}
PageLangs.List=[]
PageLangs.Names={}

PageLangs.List[PageLangs.List.length] = 'NL'
PageLangs.Names['NL']='Dutch'

