// This JavaScript file was generated by Yggdrassil on Wednesday, September 11, 2024; 11:29:52 AM

let PageLangs = {}
PageLangs.List=[]
PageLangs.Names={}

PageLangs.List[PageLangs.List.length] = 'NL'
PageLangs.Names['NL']='Dutch'

