// This JavaScript file was generated by Yggdrassil on Tuesday, December 6, 2022; 5:57:22 PM

let PageLangs = {}
PageLangs.List=[]
PageLangs.Names={}

PageLangs.List[PageLangs.List.length] = 'NL'
PageLangs.Names['NL']='Dutch'

