// This JavaScript file was generated by Yggdrassil on Friday, December 17, 2021; 2:47:08 PM

let PageLangs = {}
PageLangs.List=[]
PageLangs.Names={}

PageLangs.List[PageLangs.List.length] = 'NL'
PageLangs.Names['NL']='Dutch'

