// This JavaScript file was generated by Yggdrassil on Tuesday, May 28, 2024; 12:06:54 PM

let PageLangs = {}
PageLangs.List=[]
PageLangs.Names={}

PageLangs.List[PageLangs.List.length] = 'NL'
PageLangs.Names['NL']='Dutch'

