// This JavaScript file was generated by Yggdrassil on Saturday, December 4, 2021; 1:26:44 PM

let PageLangs = {}
PageLangs.List=[]
PageLangs.Names={}

PageLangs.List[PageLangs.List.length] = 'NL'
PageLangs.Names['NL']='Dutch'

PageLangs.List[PageLangs.List.length] = 'EN'
PageLangs.Names['EN']='English'

