// This JavaScript file was generated by Yggdrassil on Saturday, May 11, 2024; 7:16:03 PM

let PageLangs = {}
PageLangs.List=[]
PageLangs.Names={}

PageLangs.List[PageLangs.List.length] = 'NL'
PageLangs.Names['NL']='Dutch'

