// This JavaScript file was generated by Yggdrassil on Tuesday, May 28, 2024; 11:45:17 AM

let PageLangs = {}
PageLangs.List=[]
PageLangs.Names={}

PageLangs.List[PageLangs.List.length] = 'NL'
PageLangs.Names['NL']='Dutch'

