// This JavaScript file was generated by Yggdrassil on Saturday, December 11, 2021; 4:40:35 PM

let PageLangs = {}
PageLangs.List=[]
PageLangs.Names={}

PageLangs.List[PageLangs.List.length] = 'NL'
PageLangs.Names['NL']='Dutch'

