// This JavaScript file was generated by Yggdrassil on Friday, August 5, 2022; 4:38:13 PM

let PageLangs = {}
PageLangs.List=[]
PageLangs.Names={}

PageLangs.List[PageLangs.List.length] = 'NL'
PageLangs.Names['NL']='Dutch'

