// This JavaScript file was generated by Yggdrassil on Tuesday, December 6, 2022; 8:31:48 PM

let PageLangs = {}
PageLangs.List=[]
PageLangs.Names={}

PageLangs.List[PageLangs.List.length] = 'NL'
PageLangs.Names['NL']='Dutch'

PageLangs.List[PageLangs.List.length] = 'EN'
PageLangs.Names['EN']='English'

PageLangs.List[PageLangs.List.length] = 'DE'
PageLangs.Names['DE']='German'

PageLangs.List[PageLangs.List.length] = 'FR'
PageLangs.Names['FR']='French'

PageLangs.List[PageLangs.List.length] = 'ES'
PageLangs.Names['ES']='Spanish'

