// This JavaScript file was generated by Yggdrassil on Saturday, December 4, 2021; 2:05:22 PM

let PageLangs = {}
PageLangs.List=[]
PageLangs.Names={}

PageLangs.List[PageLangs.List.length] = 'NL'
PageLangs.Names['NL']='Dutch'

