// This JavaScript file was generated by Yggdrassil on Tuesday, December 6, 2022; 5:56:51 PM

let PageLangs = {}
PageLangs.List=[]
PageLangs.Names={}

PageLangs.List[PageLangs.List.length] = 'NL'
PageLangs.Names['NL']='Dutch'

PageLangs.List[PageLangs.List.length] = 'EN'
PageLangs.Names['EN']='English'

