// This JavaScript file was generated by Yggdrassil on Saturday, April 20, 2024; 4:38:19 PM

let PageLangs = {}
PageLangs.List=[]
PageLangs.Names={}

PageLangs.List[PageLangs.List.length] = 'NL'
PageLangs.Names['NL']='Dutch'

